'use client'

import { DomainLayout } from '@/components/layout/DomainLayout'
import { DomainBreadcrumb } from '@/components/layout/DomainBreadcrumb'
import { ScrollReveal } from '@/components/shared/ScrollReveal'
type Complexity = 'Low' | 'Medium' | 'High'

interface Workflow {
  title: string
  description: string
  stack: string[]
  complexity: Complexity
}

interface GhSnippet {
  title: string
  yaml: string
}

const cicdWorkflows: Workflow[] = [
  {
    title: 'Typecheck + Lint + Test → Build → Lighthouse CI',
    description:
      'Three-stage GitHub Actions pipeline: quality gate (tsc, eslint, vitest) runs first; build job depends on quality passing; Lighthouse CI job audits the static export for performance, accessibility, and SEO regressions.',
    stack: ['GitHub Actions', 'Node 22', 'Vitest', 'Lighthouse CI', 'Next.js'],
    complexity: 'Medium',
  },
  {
    title: 'Docker Multi-stage Build with Layer Cache',
    description:
      'Uses BuildKit multi-stage Dockerfile — deps stage caches node_modules separately from the build stage. GitHub Actions cache action stores Docker layers between runs, cutting cold build time by 60–80%.',
    stack: ['Docker', 'BuildKit', 'GitHub Actions', 'Node.js'],
    complexity: 'Medium',
  },
  {
    title: 'Semantic Release with Changelog Generation',
    description:
      'Conventional Commits trigger semantic-release on merge to main. Automatically bumps semver, generates CHANGELOG.md, creates GitHub Release, and publishes to npm — zero manual version management.',
    stack: ['semantic-release', 'Conventional Commits', 'GitHub Actions', 'npm'],
    complexity: 'Low',
  },
]

const n8nWorkflows: Workflow[] = [
  {
    title: 'GitHub Issue → Auto-label → Notify Slack',
    description:
      'Webhook triggers on issue open. GPT-4o classifies the issue type (bug/feature/docs). n8n applies the correct GitHub label via API and posts a formatted card to the #engineering Slack channel.',
    stack: ['n8n', 'GitHub API', 'OpenAI', 'Slack'],
    complexity: 'Low',
  },
  {
    title: 'RSS Feed → AI Summary → Telegram Channel',
    description:
      'Polls 5 tech RSS feeds every 6 hours. For each new item, Claude Haiku writes a 2-sentence summary with emoji. Deduplication via Redis. Posts to Telegram channel with source attribution.',
    stack: ['n8n', 'RSS', 'Claude API', 'Upstash Redis', 'Telegram'],
    complexity: 'Medium',
  },
  {
    title: 'CRM Lead → Enrich → Assign → Welcome Email',
    description:
      'New CRM lead triggers workflow. Clearbit enriches company data. Scoring logic assigns to sales rep based on company size and industry. Resend dispatches personalized welcome email with rep introduction.',
    stack: ['n8n', 'Clearbit', 'Resend', 'HubSpot'],
    complexity: 'High',
  },
  {
    title: 'Daily Metrics Digest → Email Report',
    description:
      'Runs every morning at 08:00 UTC. Pulls PostHog, GitHub, and Stripe metrics via HTTP nodes. Formats into a structured HTML report. Sends to founder inbox via Resend with key deltas highlighted.',
    stack: ['n8n', 'PostHog API', 'Stripe API', 'GitHub API', 'Resend'],
    complexity: 'Medium',
  },
  {
    title: 'New GitHub Star → Thank You Tweet (X)',
    description:
      'GitHub webhook fires on repository star. Fetches stargazer profile. Generates a personalized thank-you tweet with Claude Haiku. Posts via X API v2. Deduplication via Redis to prevent double-tweets.',
    stack: ['n8n', 'GitHub Webhook', 'Claude API', 'X API v2', 'Upstash Redis'],
    complexity: 'Medium',
  },
  {
    title: 'Nightly SEO Audit → Linear Issue Creator',
    description:
      'Runs at 02:00 UTC. Crawls the live site with Lighthouse CI. Parses results. For each failed check (score drop > 5%), creates a Linear issue with severity, affected URL, and fix suggestion generated by Claude.',
    stack: ['n8n', 'Lighthouse CI', 'Claude API', 'Linear API'],
    complexity: 'High',
  },
]

const aiPatterns: Workflow[] = [
  {
    title: 'RAG Pipeline: Ingest → Chunk → Embed → Retrieve → Generate',
    description:
      'Documents loaded and split into 512-token chunks with 64-token overlap. OpenAI text-embedding-3-small generates vectors stored in pgvector. At query time, top-k retrieval feeds context to the generation step with a structured system prompt.',
    stack: ['LangChain', 'pgvector', 'OpenAI Embeddings', 'PostgreSQL'],
    complexity: 'High',
  },
  {
    title: 'Multi-Agent Loop: Planner → Executor → Critic → Summarizer',
    description:
      'Planner breaks task into steps. Executor uses tool calls to carry each out. Critic evaluates output against acceptance criteria — loops back if needed. Summarizer produces the final structured response.',
    stack: ['Claude API', 'LangGraph', 'Tool Use', 'Python'],
    complexity: 'High',
  },
  {
    title: 'Document Classification Pipeline with Confidence Scoring',
    description:
      'Structured output forces JSON response with category, subcategory, and confidence 0–1. Documents below 0.7 confidence are queued for human review. High-confidence results route automatically to downstream workflows.',
    stack: ['Claude API', 'Zod', 'TypeScript', 'n8n'],
    complexity: 'Medium',
  },
  {
    title: 'Structured Output Pipeline with Zod Validation',
    description:
      'Force JSON output using tool_choice: tool + input schema derived from Zod. Validate at runtime with safeParse. Retry up to 3 times on validation failure — pass the Zod error back as user message for self-correction.',
    stack: ['Claude API', 'Zod', 'zodToJsonSchema', 'TypeScript'],
    complexity: 'Low',
  },
  {
    title: 'Streaming Agent with Real-Time UI Updates',
    description:
      'Use streaming API to show agent reasoning in real time. Parse stream chunks for tool_use blocks. Execute tools mid-stream and inject results. React to tool output before final response arrives.',
    stack: ['Claude Streaming API', 'React', 'Server-Sent Events', 'Next.js'],
    complexity: 'High',
  },
]

const ghSnippets: GhSnippet[] = [
  {
    title: 'Quality Gate (3-stage pipeline)',
    yaml: `name: CI
on: [push, pull_request]
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22', cache: 'npm' }
      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run test
  build:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22', cache: 'npm' }
      - run: npm ci && npm run build
      - uses: actions/upload-artifact@v4
        with: { name: dist, path: dist/ }
  lighthouse:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { name: dist, path: dist/ }
      - run: npx lhci autorun`,
  },
  {
    title: 'Auto-label PRs by size',
    yaml: `name: PR Labels
on: pull_request
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          xs_max_size: 10
          s_max_size: 50
          m_max_size: 200
          l_max_size: 500`,
  },
  {
    title: 'Deploy on merge to main',
    yaml: `name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22', cache: 'npm' }
      - run: npm ci && npm run build
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: my-portfolio
          directory: dist`,
  },
]

const dockerComposeSnippet = `version: '3.9'

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://app:secret@postgres:5432/appdb
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres: { condition: service_healthy }
      redis:    { condition: service_started }
    networks: [backend]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(\`example.com\`)"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [backend]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks: [backend]

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_certs:/etc/letsencrypt:ro
    ports: ["80:80", "443:443"]
    depends_on: [app]
    networks: [backend]

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
    entrypoint: >
      /bin/sh -c "trap exit TERM;
      while :; do certbot renew --webroot -w /var/www/certbot;
      sleep 12h & wait \$!; done"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports: ["9090:9090"]
    networks: [backend]

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports: ["3001:3000"]
    depends_on: [prometheus]
    networks: [backend]

volumes:
  postgres_data:
  redis_data:
  certbot_certs:
  prometheus_data:
  grafana_data:

networks:
  backend:`

const taskfileSnippet = `version: '3'

vars:
  APP_NAME: my-app
  DOCKER_IMAGE: "{{.APP_NAME}}:latest"

tasks:
  default:
    desc: List all tasks
    cmds: [task --list]
    silent: true

  dev:
    desc: Start development server with hot reload
    cmds: [npm run dev]

  build:
    desc: Production build
    cmds: [npm run build]

  test:
    desc: Run all tests
    cmds: [npm run test -- --run]

  test:watch:
    desc: Run tests in watch mode
    cmds: [npm run test]

  lint:
    desc: Lint and auto-fix
    cmds: [npm run lint -- --fix]

  typecheck:
    desc: TypeScript type checking (no emit)
    cmds: [npm run typecheck]

  db:migrate:
    desc: Run pending database migrations
    cmds: [npx drizzle-kit migrate]

  db:seed:
    desc: Seed the database with test data
    cmds: [npx tsx src/lib/db/seed.ts]

  db:studio:
    desc: Open Drizzle Studio database GUI
    cmds: [npx drizzle-kit studio]

  docker:up:
    desc: Start all Docker Compose services
    cmds: [docker compose up -d]

  docker:down:
    desc: Stop all Docker Compose services
    cmds: [docker compose down]

  docker:logs:
    desc: Tail logs for all services
    cmds: [docker compose logs -f]

  deploy:
    desc: Deploy to production (Railway)
    deps: [typecheck, test]
    cmds:
      - echo "Deploying {{.APP_NAME}}..."
      - railway up --environment production
      - echo "Deploy complete"`

const makefileSnippet = `.PHONY: all dev build test lint typecheck clean deploy

# Default target
all: typecheck lint test build

dev:
	npm run dev

build:
	npm run build

test:
	npm run test -- --run

test-watch:
	npm run test

lint:
	npm run lint

typecheck:
	npm run typecheck

clean:
	rm -rf dist .next node_modules/.cache

install:
	npm ci

# DB operations
db-migrate:
	npx drizzle-kit migrate

db-seed:
	npx tsx src/lib/db/seed.ts

# Docker
docker-up:
	docker compose up -d

docker-down:
	docker compose down

docker-rebuild:
	docker compose up -d --build

# Deploy (requires RAILWAY_TOKEN)
deploy: typecheck test
	railway up --environment production
	@echo "Deployed successfully"`

function complexityClass(c: Complexity): string {
  if (c === 'Low') return `shrink-0 rounded-full border px-2.5 py-0.5 font-mono text-[9px] uppercase tracking-widest border-emerald-500/30 bg-emerald-500/10 text-emerald-400`
  if (c === 'High') return `shrink-0 rounded-full border px-2.5 py-0.5 font-mono text-[9px] uppercase tracking-widest border-red-500/30 bg-red-500/10 text-red-400`
  return `shrink-0 rounded-full border px-2.5 py-0.5 font-mono text-[9px] uppercase tracking-widest border-yellow-500/30 bg-yellow-500/10 text-yellow-400`
}

function Section({ label, workflows }: { label: string; workflows: Workflow[] }) {
  return (
    <div>
      <p className="mb-4 mt-10 font-mono text-[9px] uppercase tracking-[0.24em] text-primary/60" >{label}</p>
      <div className="flex flex-col gap-3">
        {workflows.map((w, i) => (
          <ScrollReveal key={w.title} delay={i * 0.06}>
            <div className="group rounded-xl border border-white/8 bg-white/[0.03] p-5 transition-all hover:bg-white/[0.06] hover:border-white/15" >
              <div className="mb-2 flex items-start justify-between gap-4">
                <span className="text-sm font-semibold text-white">{w.title}</span>
                <span className={complexityClass(w.complexity)}>{w.complexity}</span>
              </div>
              <p className="mb-3 text-xs text-muted-foreground leading-relaxed">{w.description}</p>
              <div className="flex flex-wrap gap-1.5">
                {w.stack.map(t => (
                  <span key={t} className="rounded-md bg-white/5 px-2 py-0.5 font-mono text-[10px] text-white/40" >{t}</span>
                ))}
              </div>
            </div>
          </ScrollReveal>
        ))}
      </div>
    </div>
  )
}

export default function ResourcesWorkflowsPage() {
  return (
    <DomainLayout>
      <div className="mb-12">
        <DomainBreadcrumb />
        <span className={`mt-6 block mb-6 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 py-2 font-mono text-xs uppercase tracking-[0.22em] text-primary`}>
          <span className="h-1.5 w-1.5 rounded-full bg-primary animate-pulse" />
          Resources / Workflows
        </span>
        <h1 className="text-4xl font-semibold leading-tight md:text-6xl">
          <span className="gradient-text">Automation Workflows.</span>
        </h1>
        <p className="mt-6 max-w-3xl text-lg text-muted-foreground">
          CI/CD pipelines, n8n automation templates, AI agent patterns,
          Docker Compose production stacks, and task runners. Copy, adapt, and ship faster.
        </p>
      </div>

      {/* GitHub Actions Snippets */}
      <div>
        <p className="mb-4 mt-10 font-mono text-[9px] uppercase tracking-[0.24em] text-primary/60" >GitHub Actions Snippets</p>
        <div className="flex flex-col gap-3">
          {ghSnippets.map((snippet, i) => (
            <ScrollReveal key={snippet.title} delay={i * 0.06}>
              <div className="rounded-xl border border-white/8 bg-black/30 p-4">
                <p className="mb-1.5 text-sm font-semibold text-white/70">{snippet.title}</p>
                <pre className="overflow-x-auto rounded-lg bg-black/40 p-4 font-mono text-[10.5px] leading-relaxed text-emerald-400/75 border border-white/5">{snippet.yaml}</pre>
              </div>
            </ScrollReveal>
          ))}
        </div>
      </div>

      <Section label="CI/CD Pipelines" workflows={cicdWorkflows} />
      <Section label="n8n Workflows" workflows={n8nWorkflows} />
      <Section label="AI Automation Patterns" workflows={aiPatterns} />

      {/* Docker Compose Production Stack */}
      <div>
        <p className="mb-4 mt-10 font-mono text-[9px] uppercase tracking-[0.24em] text-primary/60" >Docker Compose Production Stack</p>
        <div className="rounded-xl border border-white/8 bg-black/30 p-4">
          <p className="mb-1.5 text-sm font-semibold text-white/70">
            docker-compose.yml — App + Postgres + Redis + Nginx + Certbot + Prometheus + Grafana
          </p>
          <p className="mb-4 text-xs text-muted-foreground leading-relaxed">
            Full production compose stack with health checks, named volumes, isolated network, TLS via Let&apos;s Encrypt,
            and Prometheus + Grafana monitoring. Copy and customise for your project.
          </p>
          <pre className="overflow-x-auto rounded-lg bg-black/40 p-4 font-mono text-[10.5px] leading-relaxed text-emerald-400/75 border border-white/5">{dockerComposeSnippet}</pre>
        </div>
      </div>

      {/* Taskfile */}
      <div>
        <p className="mb-4 mt-10 font-mono text-[9px] uppercase tracking-[0.24em] text-primary/60" >Taskfile.yml — Modern Make Alternative</p>
        <div className="rounded-xl border border-white/8 bg-black/30 p-4">
          <p className="mb-1.5 text-sm font-semibold text-white/70">
            Taskfile.yml — Complete TypeScript project task runner
          </p>
          <p className="mb-4 text-xs text-muted-foreground leading-relaxed">
            Task (taskfile.dev) is a modern, cross-platform alternative to Make. YAML syntax, built-in dependency tracking,
            and works natively on Linux, macOS, and Windows.
          </p>
          <pre className="overflow-x-auto rounded-lg bg-black/40 p-4 font-mono text-[10.5px] leading-relaxed text-emerald-400/75 border border-white/5">{taskfileSnippet}</pre>
        </div>
      </div>

      {/* Makefile */}
      <div>
        <p className="mb-4 mt-10 font-mono text-[9px] uppercase tracking-[0.24em] text-primary/60" >Makefile — Classic Build Automation</p>
        <div className="rounded-xl border border-white/8 bg-black/30 p-4">
          <p className="mb-1.5 text-sm font-semibold text-white/70">
            Makefile — Phony targets for TypeScript + Docker + Deploy
          </p>
          <p className="mb-4 text-xs text-muted-foreground leading-relaxed">
            Classic Makefile with .PHONY declarations for a TypeScript project. Includes dev, build, test, lint, typecheck,
            database operations, Docker management, and deployment.
          </p>
          <pre className="overflow-x-auto rounded-lg bg-black/40 p-4 font-mono text-[10.5px] leading-relaxed text-emerald-400/75 border border-white/5">{makefileSnippet}</pre>
        </div>
      </div>
    </DomainLayout>
  )
}
