import type { GitHubIntelligence } from '@/lib/github/types'

export const mockGitHubIntelligence: GitHubIntelligence = {
  revision: 'phase-5-github-intelligence',
  generatedAt: new Date().toISOString(),
  source: 'mock',
  repositories: [
    {
      name: 'trading-ai-system',
      description: 'Advanced AI-powered trading system with real-time market analysis and strategy execution.',
      stars: 234,
      forks: 45,
      language: 'Python',
      languageColor: '#3572A5',
      status: 'active',
      updatedAt: '2 hours ago',
      href: '#',
      commitVelocity: '18 commits/week',
    },
    {
      name: 'mcp-orchestrator',
      description: 'MCP infrastructure for robust multi-agent orchestration, memory flow and tool routing.',
      stars: 189,
      forks: 32,
      language: 'TypeScript',
      languageColor: '#3178C6',
      status: 'active',
      updatedAt: '5 hours ago',
      href: '#',
      commitVelocity: '22 commits/week',
    },
    {
      name: 'graph-memory-system',
      description: 'Persistent graph memory architecture for context, retrieval and reasoning continuity.',
      stars: 98,
      forks: 15,
      language: 'Python',
      languageColor: '#3572A5',
      status: 'active',
      updatedAt: '1 day ago',
      href: '#',
      commitVelocity: '11 commits/week',
    },
  ],
  totalStars: 521,
  totalForks: 92,
  commitsLast30d: 143,
  recentReleases: [
    { repository: 'trading-ai-system', tagName: 'v2.4.1', publishedAt: '2026-05-14', url: '#' },
    { repository: 'mcp-orchestrator', tagName: 'v1.9.0', publishedAt: '2026-05-12', url: '#' },
  ],
  deployments: [
    { repository: 'trading-ai-system', environment: 'production', state: 'success', updatedAt: '2026-05-17T19:20:00Z' },
    { repository: 'mcp-orchestrator', environment: 'staging', state: 'success', updatedAt: '2026-05-17T18:10:00Z' },
    { repository: 'graph-memory-system', environment: 'production', state: 'queued', updatedAt: '2026-05-17T17:55:00Z' },
  ],
  activity: [
    { date: '2026-05-11', commits: 6 },
    { date: '2026-05-12', commits: 9 },
    { date: '2026-05-13', commits: 7 },
    { date: '2026-05-14', commits: 11 },
    { date: '2026-05-15', commits: 8 },
    { date: '2026-05-16', commits: 5 },
    { date: '2026-05-17', commits: 10 },
  ],
}
