import type { AdminState, StudioConfig } from './types'
import { VPS_SYNC_IDLE } from './types'
import {
  defaultSystemsRegistry,
  defaultLabsRegistry,
  defaultProjectsRegistry,
  defaultResearchRegistry,
  defaultToolRegistry,
  defaultRepoRegistry,
  defaultWorkflowRegistry,
  defaultPromptRegistry,
  defaultMcpRegistry,
  defaultAgentRegistry,
  defaultSkillRegistry,
} from './defaults/registries'
import {
  defaultInfraConfig,
  defaultNavigation,
  defaultEffects,
} from './defaults/infrastructure'
import {
  defaultBlocks,
  defaultPageBlocksMap,
  defaultSiteContent,
  defaultNavbarSettings,
  defaultFooterSettings,
} from './defaults/content'
import {
  defaultAIConfig,
  defaultIntegrations,
  defaultCapabilities,
} from './defaults/services'
import { defaultVisualEffects, defaultHeroSceneConfig, defaultPageEffectsMap } from './defaults/effects'
import { defaultIntelligenceConfig } from './defaults/intelligence'

// Re-export for backwards-compatibility with existing importers
export { defaultPageBlocksMap } from './defaults/content'

// ─── Studio Config Default ────────────────────────────────────────────────────

export const defaultStudioConfig: StudioConfig = {
  sidebarWidth:       'normal',
  density:            'normal',
  headerHeight:       'md',
  contentMaxWidth:    'xl',
  panelPadding:       'normal',
  backgroundStyle:    'midnight',
  sidebarStyle:       'solid',
  accentColor:        '#22d3ee',
  useCustomAccent:    false,
  fontFamily:         'mono',
  fontSize:           'sm',
  borderRadius:       'normal',
  glowEffect:              false,
  glowOpacity:             25,
  sidebarBorder:           true,
  activePreset:            '',
  animations:              true,
  showDescriptions:        true,
  rememberLastPanel:       true,
  keyboardShortcuts:       true,
  showSavedIndicator:      true,
  confirmReset:            true,
  autoSaveMs:              800,
  showTooltips:            true,
  sidebarCollapsedDefault: false,
  sidebarHoverExpand:      false,
  headerShowClock:         false,
  compactHeader:           false,
  panelTransition:         'fade',
  scrollbarStyle:          'thin',
  animationSpeed:          'normal',
  showPanelBadges:         false,
  sidebarFooter:           true,
  reducedMotion:           false,
  highContrast:            false,
  defaultPanel:       'command',
  showGroupDividers:  true,
  pinnedPanels:       [],
  customPresets:      [],
  workspaceProfiles:  [],
  navGroups: [
    { key: 'content',      visible: true, collapsed: false, order: 0 },
    { key: 'operations',   visible: true, collapsed: false, order: 1 },
    { key: 'site-builder', visible: true, collapsed: true,  order: 2 },
    { key: 'advanced',     visible: true, collapsed: true,  order: 3 },
    { key: 'studio',       visible: true, collapsed: false, order: 4 },
  ],
  panelOverrides: [],
  headerActions: {
    showExport: true,
    showImport: true,
    showBackup: true,
    showReset:  true,
    showSearch: true,
  },
}

// ─── Initial State ────────────────────────────────────────────────────────────

export const createInitialState = (): AdminState => ({
  panel: 'command',
  site: {
    name: 'JootaCee',
    url: 'https://jootacee.com',
    description: 'Operational laboratory for AI systems, automation infrastructures, and modular digital ecosystems.',
    businessFocus: 'AI Systems Architecture & Automation Infrastructure',
    trackingId: '',
    enableAnalytics: true,
    enableTelemetry: true,
    maintenanceMode: false,
  },
  seo: {
    titleTemplate: '%s | JootaCee',
    defaultTitle: 'JootaCee | AI Systems Architect',
    defaultDescription: 'Operational laboratory for AI systems, automation infrastructures, and modular digital ecosystems.',
    ogImage: '/og-image.png',
    twitterHandle: '@jootacee',
    robots: 'index, follow',
    canonicalBase: 'https://jootacee.com',
  },
  runtime: {
    version: 'v2.1.0',
    environment: 'production',
    deployedAt: '2026-05-24T09:14:00.000Z',
    activeAgents: 0,
    mcpTools: 0,
    systemsOnline: 0,
  },
  projectsRegistry: defaultProjectsRegistry,
  systemsRegistry: defaultSystemsRegistry,
  labsRegistry: defaultLabsRegistry,
  researchRegistry: defaultResearchRegistry,
  toolRegistry:     defaultToolRegistry,
  repoRegistry:     defaultRepoRegistry,
  workflowRegistry: defaultWorkflowRegistry,
  promptRegistry:   defaultPromptRegistry,
  mcpRegistry:      defaultMcpRegistry,
  agentRegistry:    defaultAgentRegistry,
  skillRegistry:    defaultSkillRegistry,
  infraConfig: defaultInfraConfig,
  githubConfig: {
    username: 'jootaceehub',
    accessToken: '',
    displayRepos: ['worldmonitor', 'hermes-agent', 'jootaceehub', 'react-oauth', '3d-model-generator', 'threejs-skills'],
    repoMeta: {
      'worldmonitor':       { description: 'Real-time global intelligence dashboard. AI-powered news aggregation and infrastructure tracking.', language: 'TypeScript', stars: 0, forks: 0, topics: ['ai', 'dashboard', 'intelligence'],  pinned: true  },
      'hermes-agent':       { description: 'The agent that grows with you',                                                                     language: 'Python',     stars: 0, forks: 0, topics: ['ai', 'agent', 'llm'],              pinned: true  },
      'jootaceehub':        { description: 'Personal hub and portfolio — Next.js 16 with i18n, admin CMS and PWA support',                      language: 'TypeScript', stars: 0, forks: 0, topics: ['portfolio', 'nextjs', 'cms'],     pinned: false },
      'react-oauth':        { description: 'Google OAuth2 using the new Google Identity Services SDK for React',                                 language: 'TypeScript', stars: 2, forks: 0, topics: ['oauth', 'react', 'google'],       pinned: false },
      '3d-model-generator': { description: 'AI-powered 3D model generator',                                                                     language: 'TypeScript', stars: 0, forks: 0, topics: ['3d', 'ai', 'generator'],         pinned: false },
      'threejs-skills':     { description: 'Three.js skills and interactive experiments',                                                        language: 'TypeScript', stars: 0, forks: 0, topics: ['threejs', '3d', 'webgl'],        pinned: false },
    },
    // Section visibility
    showProfileCard: true,
    showContributions: true,
    showStats: true,
    showActivity: true,
    showLanguages: true,
    showTopics: true,
    showForks: false,
    showStarred: true,
    showOwnRepos: true,
    showCommitActivity: false,
    showRecentReleases: false,
    showDeployments: false,
    // Page hero
    pageBadge: 'Open Source',
    pageHeadline: 'GitHub',
    pageSubheadline: 'Open source projects, activity, and curated repositories.',
    // Curated repos section
    ownReposTitle: 'My Repositories',
    ownReposSubtitle: 'Open source projects I maintain and develop.',
    ownReposLimit: 6,
    // Starred section
    starredTitle: 'Repos Recomendados',
    starredSubtitle: 'Proyectos y herramientas que personalmente he marcado como favoritos.',
    showStarredCategories: true,
    // Display
    statSlot4: 'starred',
    activityLimit: 10,
    displayMode: 'list',
  },
  blocks: defaultBlocks,
  pageBlocksMap: defaultPageBlocksMap,
  content: defaultSiteContent,
  navbarSettings: defaultNavbarSettings,
  footerSettings: defaultFooterSettings,
  navigation: defaultNavigation,
  design: {
    darkModeDefault: 'dark',
    palette: 'ocean',
    customPrimary: '#4ba8ff',
    customSecondary: '#7ed8ff',
    customAccent: '#ffd166',
    customBackground: '#060610',
    customSurface: '#0d0d1a',
    customText: '#e2e8f0',
    customBorder: '#1e2035',
    customGlow: '',
    customGlowSecondary: '',
    customRing: '',
    customMuted: '',
    customMutedFg: '',
    gradientStart: '',
    gradientMid: '',
    gradientEnd: '',
    btnGradientFrom: '',
    btnGradientTo: '',
    btnText: '',
    domainAccents: {
      projects: '#a78bfa',
      research: '#34d399',
      resources: '#38bdf8',
      intelligence: '#facc15',
      github: '#f472b6',
      about: '#94a3b8',
    },
    tokens: {
      borderRadius: 'xl',
      spacingScale: 'normal',
      shadowIntensity: 'subtle',
      glowIntensity: 'normal',
      gradientStyle: 'subtle',
      buttonStyle: 'pill',
      typography: 'modern',
      fontSizeScale: 'md',
      animationSpeed: 'normal',
      containerWidth: 'xl',
      cardStyle: 'elevated',
      inputStyle: 'outlined',
      sectionPadding: 'normal',
      glassBlur: 'md',
      glassOpacity: 'normal',
      glassBorderOpacity: 'normal',
    },
  },
  personality: {
    active: 'futuristic',
    effects: defaultEffects,
    designGuide: 'Maintain high contrast, generous whitespace, and subtle motion. Prioritize readability and hierarchy. Use glassmorphism sparingly on dark backgrounds.',
  },
  curatedLinks: [],
  driveResources: [],
  trackedSources: [],
  aboutConfig: {
    headline: 'AI Systems Architect',
    bio: 'Building autonomous systems, modular AI infrastructure, and intelligent automation pipelines. Focused on bridging engineering depth with product thinking.',
    location: 'Remote',
    availability: 'available',
    skills: ['TypeScript', 'Python', 'Next.js', 'React', 'Node.js', 'Docker', 'PostgreSQL'],
    tools: ['Claude AI', 'n8n', 'Supabase', 'Vercel', 'GitHub', 'MCP Protocol'],
    certifications: [],
    collaborationTypes: ['AI Systems', 'Automation', 'Full-Stack', 'Consulting'],
    timeline: [],
  },
  aiConfig: defaultAIConfig,
  integrations: defaultIntegrations,
  capabilities: defaultCapabilities,
  visualEffects: defaultVisualEffects,
  heroSceneConfig: defaultHeroSceneConfig,
  pageEffectsMap: defaultPageEffectsMap,
  intelligence: defaultIntelligenceConfig,
  editingPostId: null,
  intakeType: null,
  tagRegistry: [],
  categoryRegistry: [],
  mediaRegistry: [],
  seriesRegistry: [],
  revisionLog: [],
  studioConfig: defaultStudioConfig,
  unsaved: false,
  lastSaved: null,
  vpsStatus: VPS_SYNC_IDLE,
})
